export enum Links {
  facebook = "https://www.facebook.com/comp3interactive",
  instagram = "https://www.instagram.com/comp3interactive",
  youtube = "https://www.youtube.com/comp3interactive",
  github = "https://www.github.com/comp3interactive",
  itch = "https://comp3interactive.itch.io",
  patreon = "https://www.patreon.com/comp3interactive",
  googleplay = "https://play.google.com/store/apps/dev?id=7011346453411226050",
  discord = "https://discord.gg/wWFsdYy",
  twitter = "https://www.twitter.com/comp3int",
  behindClosedDoorsTwitter = "https://www.twitter.com/BCD_Game",
  invaders = "https://www.youtube.com/playlist?list=PLfhbBaEcybmhGhADxKSqqliuCLg3xY_ep",
  wordDrop = "https://play.google.com/store/apps/details?id=com.Comp3Interactive.WordDrop&hl=en_GB&gl=US",
  ascension = "https://play.google.com/store/apps/details?id=com.Comp3Interactive.Ascension&hl=en_GB&gl=US",
  invadersGame = "https://play.google.com/store/apps/details?id=com.Comp3Interactive.InvadersFromOuterspace&hl=en_GB&gl=US",
  linkedin = "https://www.linkedin.com/in/michael-lythgoe/",
}
